name: Build

on:
  pull_request:
    branches: [ master, main, bodl ]
  push:
    branches: [ master, main, bodl ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Set npm registry
        run: echo "@bigcommerce-labs:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      - name: Set npm secrets
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.CUSTOM_GA_TOKEN }}" >> ~/.npmrc
    
      - name: Install Dependencies
        run: npm i
      - name: Lint the code
        run: npm run lint

      - name: Run test with coverage
        run: npm run test-with-coverage
